### ISSUE TITLE
Dataverse URL handling & UX improvements

### ISSUE THREAD

**Issue by haarli** [MPDL/upverse#20]
The links to edmond.mpdl.mpg.de are currently hardcoded for clicks on the logo in the upper left corner and for clicks on "Open Edmond" (after files are uploaded). 
However, as it is possible to use arbitrary Dataverse instances, the links should point to the Dataverse instance given in the settings tab.

Further to discuss:
- It might be easier if the URL in settings tab points to the Dataverse instance, not to the api. The "/api" can be internally added.?
- "Open Dataset" instead of "Open Edmond"?
  - Open OS default browser instead of Electron window
- Automatically open settings tab the first time UpVerse is started (as long as it is not filled out)?

**Comment by vilarodr** [comment]
All the discussion points treated on the last meeting in addition to the above mentioned are applied on the last commit:
[https://github.com/MPDL/upverse/commit/69db6ded5f0374016a02fb464b240ee4cb9e6ed6](https://github.com/MPDL/upverse/commit/69db6ded5f0374016a02fb464b240ee4cb9e6ed6)

**Comment by hofmannc** [comment]
Server: upverse-1.0.0.Setup.exe - build package release #55
OS: Windows
Testdate: 29.06.2023
User: Hofmann, Catherina

Test result: 
It might be easier if the URL in settings tab points to the Dataverse instance, not to the api. The "/api" can be internally added.?  ->ok 
"Open Dataset" instead of "Open Edmond"? -> ok
Open OS default browser instead of Electron window -> ok
Automatically open settings tab the first time UpVerse is started (as long as it is not filled out)? -> ok

**Comment by helkv** [comment]
Version: [v1.0.0](https://github.com/MPDL/upverse/releases/tag/v1.0.0) (https://github.com/MPDL/upverse/commit/c835405ed66050556a6a0810c2d466e73c88d466)
OS: Linux & Mac
Testdate: 20.07.2023
User: User
Test result: ok
